INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B003', '1B003');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0030 ตรวจคัดกรองได้ผลปกติ ผู้รับบริการเคยตรวจด้วยตนเองได้ผลปกติ', '1B0030');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0031 ตรวจคัดกรองได้ผลปกติ ผู้รับบริการเคยตรวจด้วยตนเองได้ผลผิดปกติ', '1B0031');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0032 ตรวจคัดกรองได้ผลปกติ ผู้รับบริการไม่เคยตรวจด้วยตนเอง', '1B0032');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0033 ตรวจคัดกรองได้ผลปกติ ไม่ระบุว่าผู้รับบริการเคยตรวจด้วยตนเองหรือไม่', '1B0033');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0034 ตรวจคัดกรองได้ผลผิดปกติ ผู้รับบริการเคยตรวจด้วยตนเองได้ผลปกติ', '1B0034');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0035 ตรวจคัดกรองได้ผลผิดปกติ ผู้รับบริการเคยตรวจด้วยตนเองได้ผลผิดปกติ', '1B0035');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0036 ตรวจคัดกรองได้ผลผิดปกติ ผู้รับบริการไม่เคยตรวจด้วยตนเอง', '1B0036');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0037 ตรวจคัดกรองได้ผลผิดปกติ ไม่ระบุว่าผู้รับบริการเคยตรวจด้วยตนเองหรือไม่', '1B0037');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0039 ตรวจคัดกรองมะเร็งเต้านม ไม่ระบุรายละเอียด', '1B0039');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B004', '1B004');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0040 ตรวจคัดกรอง VIA ได้ผลลบ', '1B0040');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0041  ตรวจคัดกรอง VIA ได้ผลบวก ไม่ให้การรักษา', '1B0041');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0042 ตรวจคัดกรอง VIA ได้ผลบวก และให้การรักษา', '1B0042');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0043  ตรวจคัดกรอง VIA ไม่ระบุผลการตรวจ', '1B0043');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0044 ตรวจคัดกรอง Pap (ยังไม่ทราบผล)', '1B0044');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0045 การคัดกรองมะเร็งปากมดลูก ด้วยวิธี VIA ผลตรวจเป็นมะเร็งปากมดลูก', '1B0045');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0048 ตรวจคัดกรอง วิธีอื่น (ระบุวิธี)', '1B0048');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0049 ตรวจคัดกรอง ไม่ระบุวิธี', '1B0049');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B026', '1B026');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0260 การประเมินภาวะซึมเศร้าด้วยแบบประเมิน 9Q พบว่าผลปกติ', '1B0260');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0261 การประเมินภาวะซึมเศร้าด้วยแบบประเมิน 9Q พบว่าซึมเศร้าน้อย (คะแนน 7-12)', '1B0261');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0262 การประเมินภาวะซึมเศร้าด้วยแบบประเมิน 9Q พบว่าซึมเศร้าปานกลาง (คะแนน 13-18)', '1B0262');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0263 การประเมินภาวะซึมเศร้าด้วยแบบประเมิน 9Q พบว่าซึมเศร้ารุนแรง (คะแนน?19)', '1B0263');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0269 การประเมินภาวะซึมเศร้าด้วยแบบประเมิน 9Q ไม่ระบุรายละเอียด', '1B0269');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B027', '1B027');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0270 การประเมินการฆ่าตัวตายด้วยแบบประเมิน 8Q พบว่าไม่มีแนวโน้มการฆ่าตัวตาย', '1B0270');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0271 การประเมินการฆ่าตัวตายด้วยแบบประเมิน 8Q พบว่ามีแนวโน้มที่จะฆ่าตัวตายระดับน้อย (คะแนน 1-8)', '1B0271');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0272 การประเมินการฆ่าตัวตายด้วยแบบประเมิน 8Q พบว่ามีแนวโน้มที่จะฆ่าตัวตายระดับปานกลาง (คะแนน 9-16)', '1B0272');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0273 การประเมินการฆ่าตัวตายด้วยแบบประเมิน 8Q พบว่ามีแนวโน้มที่จะฆ่าตัวตายระดับรุนแรง (คะแนน ?17)', '1B0273');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0279 การประเมินการฆ่าตัวตายด้วยแบบประเมิน 8Q ไม่ระบุรายละเอียด', '1B0279');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B028', '1B028');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0280 การตรวจคัดกรองโรคซึมเศร้าในผู้สูงอายุด้วยแบบคัดกรอง 2Q พบว่าผลปกติ', '1B0280');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0281 การตรวจคัดกรองโรคซึมเศร้าในผู้สูงอายุด้วยแบบคัดกรอง 2Q พบว่าผลผิดปกติ', '1B0281');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0282 การตรวจคัดกรองโรคซึมเศร้าในผู้สูงอายุด้วยแบบคัดกรอง 9Q พบว่าผลปกติ', '1B0282');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0283 การตรวจคัดกรองโรคซึมเศร้าในผู้สูงอายุด้วยแบบคัดกรอง 9Q พบว่าซึมเศร้าน้อย (คะแนน 7-12)', '1B0283');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0284 การตรวจคัดกรองโรคซึมเศร้าในผู้สูงอายุด้วยแบบคัดกรอง 9Q พบว่าซึมเศร้าปานกลาง (คะแนน 13-18)', '1B0284');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0285 การตรวจคัดกรองโรคซึมเศร้าในผู้สูงอายุด้วยแบบคัดกรอง 9Q พบว่าซึมเศร้ารุนแรง (คะแนน ?19)', '1B0285');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0286 การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในผู้สูงอายุ พบว่าผลปกติ', '1B0286');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0287 การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในผู้สูงอายุ พบว่าผลผิดปกติ', '1B0287');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0289 การตรวจคัดกรองโรคซึมเศร้า/ประเมินความเครียดในผู้สูงอายุ ไม่ระบุรายละเอียด', '1B0289');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B113', '1B113');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1130 การตรวจคัดกรองสมรรถภาพการมองเห็น ผลเหมาะสมกับลักษณะงาน', '1B1130');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1131 การตรวจคัดกรองสมรรถภาพการมองเห็น ผลไม่เหมาะสมกับลักษณะงาน', '1B1131');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1139 การตรวจคัดกรองสมรรถภาพการมองเห็น ไม่ระบุรายละเอียด', '1B1139');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B114', '1B114');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1140 การตรวจคัดกรองสมรรถภาพการได้ยินของการตรวจที่มีผลครั้งเดียว มีผลปกติ (ระดับการได้ยินไม่เกิน 25dB ทุกความถี่)', '1B1140');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1141 การตรวจคัดกรองสมรรถภาพการได้ยินของการตรวจที่มีผลครั้งเดียว มีผลตรวจไม่ผ่าน เกณฑ์ต้องส่งพบแพทย์', '1B1141');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1142 การตรวจคัดกรองสมรรถภาพการได้ยิน มีผลผ่านเกณฑ์ เมื่อเทียบผลการตรวจกับ Baseline audiogram (ไม่พบ 15 dB-shift หรือ ไม่พบ 15 dB-shift Twice ทุกความถี่) ', '1B1142');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1143 การตรวจคัดกรองสมรรถภาพการได้ยิน มีผลไม่ผ่านเกณฑ์ เมื่อเทียบผลการตรวจกับ Baseline audiogram (พบ 15 dB-shift Twice หลังจากตรวจยืนยัน: Confirmation audiogram ภายใน 30 วัน)', '1B1143');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1149 การตรวจคัดกรองสมรรถภาพทางการได้ยิน ไม่ระบุรายละเอียด', '1B1149');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B115', '1B115');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1150 การตรวจคัดกรองสมรรถภาพทางปอด ผลปกติ', '1B1150');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1151 การตรวจคัดกรองสมรรถภาพปอด ผลต่ำกว่าค่าคาดคะเนชนิดหลอดลมอุดกั้น', '1B1151');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1152 การตรวจคัดกรองสมรรถภาพปอด ผลต่ำกว่าค่าคาดคะเนชนิดจำกัดการขยายตัว', '1B1152');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1153 การตรวจคัดกรองสมรรถภาพปอด ผลต่ำกว่าค่าคาดคะเนชนิดหลอดลมอุดกั้นและจำกัดการขยายตัว (ผสม)', '1B1153');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1159 การตรวจคัดกรองสมรรถภาพทางปอด ไม่ระบุรายละเอียด', '1B1159');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B116', '1B116');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1160 การตรวจเอ็กซเรย์ปอดฟิล์มใหญ่ในวัยทำงาน ผลปกติระดับ 0/0', '1B1160');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1161 การตรวจเอ็กซเรย์ปอดฟิล์มใหญ่ในวัยทำงาน ผลผิดปกติตั้งแต่ระดับ 0/1 - 1/0', '1B1161');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1162 การตรวจเอ็กซเรย์ปอดฟิล์มใหญ่ในวัยทำงาน ผลผิดปกติตั้งแต่ระดับ 1/1 ขึ้นไป', '1B1162');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1169 การตรวจเอ็กซเรย์ปอดฟิล์มใหญ่ในวัยทำงาน ไม่ระบุรายละเอียด', '1B1169');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>', '1B117');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1170 การตรวจคัดกรองเพื่อหาความเสี่ยงจากสารกำจัดศัตรูพืช ผลปกติ', '1B1170');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1171 การตรวจคัดกรองเพื่อหาความเสี่ยงจากสารกำจัดศัตรูพืช ผลปลอดภัย', '1B1171');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1172 การตรวจคัดกรองเพื่อหาความเสี่ยงจากสารกำจัดศัตรูพืช ผลมีความเสี่ยง', '1B1172');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1173 การตรวจคัดกรองเพื่อหาความเสี่ยงจากสารกำจัดศัตรูพืช ผลไม่ปลอดภัย', '1B1173');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1179 การตรวจคัดกรองเพื่อหาความเสี่ยงจากสารกำจัดศัตรูพืช ไม่ระบุรายละเอียด', '1B1179');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B118 การตรวจคัดกรองความเสี่ยง / เฝ้าระวัง ในประชากรวัยแรงงาน อื่น ๆ', '1B118');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B119 การตรวจคัดกรองความเสี่ยง / เฝ้าระวัง ในประชากรวัยแรงงาน ไม่ระบุรายละเอียด', '1B119');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B12', '1B12');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B120', '1B120');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1200 การตรวจคัดกรองผู้สูงอายุที่มีภาวะหกล้ม พบว่าไม่มีความเสี่ยง', '1B1200');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1201 การตรวจคัดกรองผู้สูงอายุที่มีภาวะหกล้ม พบว่ามีความเสี่ยง ให้คำแนะนำและรักษา', '1B1201');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1202 การตรวจคัดกรองผู้สูงอายุที่มีภาวะหกล้ม พบว่ามีความเสี่ยงส่งรักษาต่อ', '1B1202');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1209 การตรวจคัดกรองผู้สูงอายุที่เสี่ยงภาวะหกล้มไม่ระบุรายละเอียด', '1B1209');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B122', '1B122');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1220 การตรวจคัดกรองสมรรถภาพสมอง (ภาวะสมองเสื่อม) โดยแบบAMT ในผู้สูงอายุพบว่าปกติ', '1B1220');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1221 การตรวจคัดกรองสมรรถภาพสมอง (ภาวะสมองเสื่อม) โดยแบบ AMT ในผู้สูงอายุพบว่าผิดปกติ ให้คำแนะนำและรักษา', '1B1221');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1223 การตรวจคัดกรองสมรรถภาพสมอง (ภาวะสมองเสื่อม) โดยแบบ AMT ในผู้สูงอายุพบว่าผิดปกติและส่งไปรักษาต่อ', '1B1223');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1224 การตรวจคัดกรองสมรรถภาพสมอง (ภาวะสมองเสื่อม) โดยแบบ MMSE-T 2002  ในผู้สูงอายุพบว่าปกติ', '1B1224');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1225 การตรวจคัดกรองสมรรถภาพสมอง (ภาวะสมองเสื่อม) โดยแบบ MMSE-T 2002  ในผู้สูงอายุพบว่าผิดปกติ ให้คำแนะนำและรักษา', '1B1225');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1226 การตรวจคัดกรองสมรรถภาพสมอง (ภาวะสมองเสื่อม) โดยแบบ MMSE-T 2002  ในผู้สูงอายุพบว่าผิดปกติและส่งไปรักษาต่อ', '1B1226');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1229 การตรวจคัดกรองสมรรถภาพสมอง (ภาวะสมองเสื่อม) โดยแบบ AMT/ MMSE-T 2002   ในผู้สูงอายุ ไม่ระบุรายละเอียด', '1B1229');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B123', '1B123');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1230 การตรวจคัดกรองความเสี่ยงโรคหัวใจและหลอดเลือดสมองในผู้สูงอายุ พบว่าไม่มีความเสี่ยง', '1B1230');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1231 การตรวจคัดกรองความเสี่ยงโรคหัวใจและหลอดเลือดสมองในผู้สูงอายุ พบว่ามีความเสี่ยง', '1B1231');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1232 การตรวจคัดกรองความเสี่ยงโรคหัวใจและหลอดเลือดสมองในผู้สูงอายุ พบว่ามีความเสี่ยงสูง', '1B1232');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1234 การตรวจคัดกรองความเสี่ยงโรคหัวใจและหลอดเลือดสมองในผู้สูงอายุ พบว่ามีความเสี่ยงสูงมาก ให้คำแนะนำ / รักษา', '1B1234');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1235 การตรวจคัดกรองความเสี่ยงโรคหัวใจและหลอดเลือดสมองในผู้สูงอายุพบว่ามีความเสี่ยงสูงมาก รักษาต่อ', '1B1235');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1239 การตรวจคัดกรองความเสี่ยงโรคหัวใจและหลอดเลือดสมองในผู้สูงอายุ  ไม่ระบุรายละเอียด', '1B1239');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B124', '1B124');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1240 การตรวจคัดกรองสายตาระยะใกล้ในผู้สูงอายุพบว่าไม่มีปัญหา', '1B1240');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1241 การตรวจคัดกรองสายตาระยะใกล้ในผู้สูงอายุพบว่ามีปัญหาให้คำแนะนำและรักษา', '1B1241');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1242 การตรวจคัดกรองสายตาระยะใกล้ในผู้สูงอายุพบว่ามีปัญหาส่งไปรักษาต่อ', '1B1242');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1243 การตรวจคัดกรองสายตาระยะไกลในผู้สูงอายุพบว่าไม่มีปัญหา', '1B1243');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1244 การตรวจคัดกรองสายตาระยะไกลในผู้สูงอายุพบว่ามีปัญหาให้คำแนะนำและรักษา', '1B1244');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1245 การตรวจคัดกรองสายตาระยะไกลในผู้สูงอายุพบว่ามีปัญหาส่งไปรักษาต่อ', '1B1245');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1249 การตรวจคัดกรองสายตาระยะใกล้/ระยะไกลในผู้สูงอายุไม่ระบุรายละเอียด', '1B1249');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B125', '1B125');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1250 การตรวจคัดกรองความเสี่ยงต้อกระจกในผู้สูงอายุพบว่าไม่มีปัญหา', '1B1250');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1251 การตรวจคัดกรองความเสี่ยงต้อกระจกในผู้สูงอายุพบว่ามีปัญหาให้คำแนะนำและรักษา', '1B1251');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1252 การตรวจคัดกรองความเสี่ยงต้อกระจกในผู้สูงอายุพบว่ามีปัญหาส่งไปรักษาต่อ', '1B1252');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1253 การตรวจคัดกรองความเสี่ยงต้อหินในผู้สูงอายุพบว่าไม่มีปัญหา', '1B1253');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1254 การตรวจคัดกรองความเสี่ยงต้อหินในผู้สูงอายุพบว่ามีปัญหาให้คำแนะนำและรักษา', '1B1254');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1255 การตรวจคัดกรองความเสี่ยงต้อหินในผู้สูงอายุพบว่ามีปัญหาส่งไปรักษาต่อ', '1B1255');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1256 การตรวจคัดกรองความเสี่ยงโรคจอประสาทตาเสื่อมจากอายุในผู้สูงอายุพบว่าไม่มีปัญหา', '1B1256');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1257 การตรวจคัดกรองความเสี่ยงโรคจอประสาทตาเสื่อมจากอายุในผู้สูงอายุพบว่ามีปัญหาให้คำแนะนำ และรักษา', '1B1257');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1258 การตรวจคัดกรองความเสี่ยงโรคจอประสาทตาเสื่อมจากอายุในผู้สูงอายุพบว่ามีปัญหา ส่งไปรักษาต่อ', '1B1258');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1259 การตรวจคัดกรองความเสี่ยงต้อกระจก  / ต้อหิน / จอประสาทตาเสื่อมจากอายุ ในผู้สูงอายุ ไม่ระบุรายละเอียด', '1B1259');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B126', '1B126');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1260 การตรวจคัดกรองพฤติกรรมเสี่ยงต่อสุขภาพช่องปากในผู้สูงอายุพบว่าพฤติกรรมเหมาะสม', '1B1260');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1261 การตรวจคัดกรองพฤติกรรมเสี่ยงต่อสุขภาพช่องปากในผู้สูงอายุพบว่าพฤติกรรมไม่เหมาะสม และแนะนำให้ความรู้', '1B1261');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1269 การตรวจคัดกรองพฤติกรรมเสี่ยงต่อสุขภาพช่องปากในผู้สูงอายุไม่ระบุรายละเอียด', '1B1269');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B127', '1B127');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1270 การตรวจคัดกรองข้อเข่าเสื่อมทางคลินิกในผู้สูงอายุพบว่าปกติ', '1B1270');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1271 การตรวจคัดกรองข้อเข่าเสื่อมทางคลินิกในผู้สูงอายุพบว่าผิดปกติ ให้คำแนะนำและรักษา', '1B1271');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1272 การตรวจคัดกรองข้อเข่าเสื่อมทางคลินิกในผู้สูงอายุพบว่าผิดปกติและส่งรักษาต่อ', '1B1272');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1273 การตรวจคัดกรองสมรรถนะผู้สูงอายุเกี่ยวกับการดูแลระยะยาวพบว่าไม่ต้องดูแลระยะยาว', '1B1273');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1274 การตรวจคัดกรองสมรรถนะผู้สูงอายุเกี่ยวกับการดูแลระยะยาวพบว่าต้องเฝ้าระวัง ให้คำแนะนำและติดตาม', '1B1274');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1275 การตรวจคัดกรองสมรรถนะผู้สูงอายุเกี่ยวกับการดูแลระยะยาวพบว่าต้องดูแลระยะยาว ให้คำแนะนำและดูแลต่อเนื่อง', '1B1275');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1279 การตรวจคัดกรองข้อเข่าเสื่อมทางคลินิก ในผู้สูงอายุ / สมรรถนะผู้สูงอายุเกี่ยวกับการดูแลระยะยาว ไม่ระบุรายละเอียด', '1B1279');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B128', '1B128');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1280 การตรวจคัดกรองสมรรถนะผู้สูงอายุเกี่ยวกับความสามารถในการทำกิจวัตรประจำวันพบว่าช่วยเหลือตัวเองได้ /ติดสังคม (ADL 12-20 คะแนน)', '1B1280');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1281 การตรวจคัดกรองสมรรถนะผู้สูงอายุเกี่ยวกับความสามารถในการทำกิจวัตรประจำวันพบว่าช่วยเหลือตัวเองได้บ้าง / บางส่วน /ติดบ้าน (ADL 5-11 คะแนน)', '1B1281');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1282 การตรวจคัดกรองสมรรถนะผู้สูงอายุเกี่ยวกับความสามารถในการทำกิจวัตรประจำวัน พบว่าช่วยเหลือตัวเองได้น้อย / ไม่ได้เลย /ภาวะติดเตียง (ADL 0-4 คะแนน)', '1B1282');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1289 การตรวจคัดกรองสมรรถนะผู้สูงอายุเกี่ยวกับความสามารถในการทำกิจวัตรประจำวันไม่ระบุรายละเอียด', '1B1289');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B129 การตรวจคัดกรองความเสี่ยง/เฝ้าระวังในผู้สูงอายุ ไม่ระบุรายละเอียด', '1B129');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B13', '1B13');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B130 การตรวจคัดกรองโรคซึมเศร้าในผู้ป่วยโรคเรื้อรังด้วยแบบคัดกรอง 2Q พบว่าผลปกติ', '1B130');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B131 การตรวจคัดกรองโรคซึมเศร้าในผู้ป่วยโรคเรื้อรังด้วยแบบคัดกรอง 2Q พบว่าผลผิดปกติ', '1B131');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B132 การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในผู้ป่วยโรคเรื้อรังพบว่าผลปกติ (0 ? 4 คะแนน)', '1B132');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B133 การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในผู้ป่วยโรคเรื้อรังพบว่ามีปัญหาความเครียด (5 ? 7 คะแนน)', '1B133');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B134 การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในผู้ป่วยโรคเรื้อรังพบว่ามีความเครียดสูง (8 คะแนนขึ้นไป)', '1B134');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B139 การตรวจคัดกรองโรคซึมเศร้า/ประเมินความเครียดในผู้ป่วยโรคเรื้อรังไม่ระบุรายละเอียด', '1B139');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B14', '1B14');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B140 การตรวจคัดกรองโรคซึมเศร้าในหญิงตั้งครรภ์/หลังคลอดด้วยแบบคัดกรอง 2Q พบว่าผลปกติ', '1B140');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B141 การตรวจคัดกรองโรคซึมเศร้าในหญิงตั้งครรภ์/หลังคลอดด้วยแบบคัดกรอง 2Q พบว่าผลผิดปกติ', '1B141');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B142 การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในหญิงตั้งครรภ์/หลังคลอดพบว่าผลปกติ (0 ? 4 คะแนน)', '1B142');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B143 การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในหญิงตั้งครรภ์/หลังคลอดพบว่ามีปัญหาความเครียด  (5 ? 7 คะแนน)', '1B143');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B144 การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในหญิงตั้งครรภ์/หลังคลอดพบว่ามีความเครียดสูง (8 คะแนนขึ้นไป)', '1B144');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B149 การตรวจคัดกรองโรคซึมเศร้า/ประเมินความเครียดในหญิงตั้งครรภ์/หลังคลอด ไม่ระบุรายละเอียด', '1B149');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B15', '1B15');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B150 การตรวจคัดกรองโรคซึมเศร้าในผู้มีปัญหาสุรา/สารเสพติดด้วยแบบคัดกรอง 2Q พบว่าผลปกติ', '1B150');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B151 การตรวจคัดกรองโรคซึมเศร้าในผู้มีปัญหาสุรา/สารเสพติดด้วยแบบคัดกรอง 2Q พบว่าผลผิดปกติ', '1B151');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B152 การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในผู้มีปัญหาสุรา/สารเสพติดพบว่าผลปกติ (0 ? 4 คะแนน)', '1B152');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B153 การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในผู้มีปัญหาสุรา/สารเสพติดพบว่ามีปัญหาความเครียด (5 ? 7 คะแนน)', '1B153');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B154 การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในผู้มีปัญหาสุรา/สารเสพติดพบว่ามีความเครียดสูง (8 คะแนนขึ้นไป)', '1B154');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B159 การตรวจคัดกรองโรคซึมเศร้า/ประเมินความเครียดในผู้มีปัญหาสุรา/สารเสพติดไม่ระบุรายละเอียด', '1B159');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B16', '1B16');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B160 การตรวจคัดกรองโรคซึมเศร้าในกลุ่มที่มีอาการซึมเศร้าชัดเจนด้วยแบบคัดกรอง 2Q พบว่าผลปกติ', '1B160');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B161 การตรวจคัดกรองโรคซึมเศร้าในกลุ่มที่มีอาการซึมเศร้าชัดเจนด้วยแบบคัดกรอง 2Q พบว่าผลผิดปกติ', '1B161');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B162 การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในกลุ่มที่มีอาการซึมเศร้าชัดเจนพบว่าผลปกติ (0 ? 4 คะแนน)', '1B162');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B163 การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในกลุ่มที่มีอาการซึมเศร้าชัดเจนพบว่ามีปัญหาความเครียด (5 ? 7 คะแนน)', '1B163');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B164 การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในกลุ่มที่มีอาการซึมเศร้าชัดเจนพบว่ามีความเครียดสูง (8 คะแนนขึ้นไป)', '1B164');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B169 การตรวจคัดกรองโรคซึมเศร้า/ประเมินความเครียดในกลุ่มที่มีอาการซึมเศร้า ชัดเจน ไม่ระบุรายละเอียด', '1B169');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B17', '1B17');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B170 การตรวจคัดกรองโรคซึมเศร้าในผู้ที่มีอาการทางกายเรื้อรังหลายอาการที่หาสาเหตุไม่ได้ด้วยแบบคัดกรอง 2Q พบว่าผลปกติ', '1B170');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B171 การตรวจคัดกรองโรคซึมเศร้าในผู้ที่มีอาการทางกายเรื้อรังหลายอาการที่หาสาเหตุไม่ได้ด้วยแบบคัดกรอง 2Q พบว่าผลผิดปกติ', '1B171');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B172 การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในกลุ่มที่มีอาการซึมเศร้ในผู้ที่มีอาการทางกายเรื้อรังหลายอาการที่หาสาเหตุไม่ได้ พบว่าผลปกติ (0 ? 4 คะแนน)', '1B172');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B173 การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในผู้ที่มีอาการทางกายเรื้อรังหลายอาการที่หาสาเหตุไม่ได้ พบว่ามีปัญหาความเครียด (5 ? 7 คะแนน)', '1B173');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B174  การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในผู้ที่มีอาการทางกายเรื้อรังหลายอาการที่หาสาเหตุไม่ได้ พบว่ามีความเครียดสูง (8 คะแนนขึ้นไป)', '1B174');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B179 การตรวจคัดกรองโรคซึมเศร้า/ประเมินความเครียดในผู้ที่มีอาการทางกายเรื้อรังหลายอาการที่หาสาเหตุไม่ได้  ไม่ระบุรายละเอียด', '1B179');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B18', '1B18');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B180 การตรวจคัดกรองโรคซึมเศร้าในกลุ่มที่มีการสูญเสีย  ด้วยแบบคัดกรอง 2Q พบว่าผลปกติ', '1B180');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B181 การตรวจคัดกรองโรคซึมเศร้าในกลุ่มที่มีการสูญเสีย ด้วยแบบคัดกรอง 2Q พบว่าผลผิดปกติ', '1B181');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B182 การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในกลุ่มที่มีการสูญเสีย พบว่าผลปกติ (0 ? 4 คะแนน)', '1B182');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B183 การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในกลุ่มที่มีการสูญเสีย พบว่าปัญหาความเครียด (5 ? 7 คะแนน)', '1B183');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B184 การประเมินความเครียดด้วยแบบคัดกรอง ST5 ในกลุ่มที่มีการสูญเสีย พบว่ามีความเครียดสูง (8 คะแนนขึ้นไป)', '1B184');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B189 การตรวจคัดกรองโรคซึมเศร้า/ประเมินความเครียดในกลุ่มที่มีการสูญเสีย  ไม่ระบุรายละเอียด', '1B189');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B2', '1B2');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B20', '1B20');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B200 การตรวจคัดกรองพัฒนาการสมวัยด้านการเคลื่อนไหวโดยเครื่องมือ DSPM ผลปกติ', '1B200');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B201 การตรวจคัดกรองพัฒนาการสมวัยด้านการเคลื่อนไหวโดยเครื่องมือ DSPM สงสัยล่าช้า ส่งเสริมพัฒนาการใน 1 เดือน', '1B201');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B202 การตรวจคัดกรองพัฒนาการสมวัยด้านการเคลื่อนไหวโดยเครื่องมือ DSPM ผลล่าช้า ส่งเพื่อประเมิน/รักษาต่อ', '1B202');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B203 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการเคลื่อนไหวโดยเครื่องมือ DSPMผลปกติ', '1B203');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B204 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการเคลื่อนไหวโดยเครื่องมือ DSPM สงสัยล่าช้า ส่งเสริมพัฒนาการใน 1 เดือน', '1B204');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B205 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการเคลื่อนไหวโดยเครื่องมือ DSPM ผลล่าช้า ส่งเพื่อประเมิน/รักษาต่อ', '1B205');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B206 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการเคลื่อนไหวโดยเครื่องมือ DAIM ผลปกติ', '1B206');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B207 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการเคลื่อนไหวโดยเครื่องมือ DAIM ผลล่าช้า ส่งเพื่อประเมิน/รักษาต่อ', '1B207');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B21', '1B21');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B210 การตรวจคัดกรองพัฒนาการสมวัยด้านกล้ามเนื้อมัดเล็กและสติปัญญาโดยเครื่องมือ DSPM ผลปกติ', '1B210');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B211 การตรวจคัดกรองพัฒนาการสมวัยด้านกล้ามเนื้อมัดเล็กและสติปัญญาโดยเครื่องมือ DSPM สงสัยล่าช้า ส่งเสริมพัฒนาการใน 1 เดือน', '1B211');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B212 การตรวจคัดกรองพัฒนาการสมวัยด้านกล้ามเนื้อมัดเล็กและสติปัญญาโดยเครื่องมือ DSPM ผลล่าช้า ส่งเพื่อประเมิน/รักษาต่อ', '1B212');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B213 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านกล้ามเนื้อมัดเล็กและสติปัญญาโดยเครื่องมือ DSPM ผลปกติ', '1B213');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B214 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านกล้ามเนื้อมัดเล็กและสติปัญญาโดยเครื่องมือ DSPM สงสัยล่าช้า ส่งเสริมพัฒนาการใน 1 เดือน', '1B214');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B215 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านกล้ามเนื้อมัดเล็กและสติปัญญาโดยเครื่องมือ DSPM ผลล่าช้า ส่งเพื่อประเมิน/รักษาต่อ', '1B215');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B216 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านกล้ามเนื้อมัดเล็กและสติปัญญาโดยเครื่องมือ DAIM ผลปกติ', '1B216');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B217 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านกล้ามเนื้อมัดเล็กและสติปัญญาโดยเครื่องมือ DAIM ผลล่าช้า ส่งเพื่อประเมิน/รักษาต่อ', '1B217');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B219 การตรวจคัดกรอง/แบบเฝ้าระวังพัฒนาการสมวัยด้านกล้ามเนื้อมัดเล็กและสติปัญญาโดยเครื่องมือ DSPM และหรือ DAIM ไม่ระบุรายละเอียด', '1B219');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B22', '1B22');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B220 การตรวจคัดกรองพัฒนาการสมวัยด้านการเข้าใจภาษาโดยเครื่องมือ DSPM ผลปกติ', '1B220');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B221 การตรวจคัดกรองพัฒนาการสมวัยด้านการเข้าใจภาษาโดยเครื่องมือ DSPM สงสัยล่าช้า ส่งเสริมพัฒนาการใน 1 เดือน', '1B221');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B222 การตรวจคัดกรองพัฒนาการสมวัยด้านการเข้าใจภาษาโดยเครื่องมือ DSPM ผลล่าช้า ส่งเพื่อประเมิน/รักษาต่อ', '1B222');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B223 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการเข้าใจภาษาโดยเครื่องมือ DSPM ผลปกติ', '1B223');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B224 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการเข้าใจภาษาโดยเครื่องมือ DSPM สงสัยล่าช้า ส่งเสริมพัฒนาการใน 1 เดือน', '1B224');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B225 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการเข้าใจภาษาโดยเครื่องมือ DSPM ผลล่าช้า ส่งเพื่อประเมิน/รักษาต่อ', '1B225');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B226 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการเข้าใจภาษาโดยเครื่องมือ DAIM ผลปกติ', '1B226');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B227 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการเข้าใจภาษาโดยเครื่องมือ DAIM ผลล่าช้า ส่งเพื่อประเมิน/รักษาต่อ', '1B227');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B229 การตรวจคัดกรอง/แบบเฝ้าระวังพัฒนาการสมวัยด้านการเข้าใจภาษาโดยเครื่องมือ DSPM และหรือ DAIM ไม่ระบุรายละเอียด', '1B229');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B23', '1B23');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B230 การตรวจคัดกรองพัฒนาการสมวัยด้านการใช้ภาษาโดยเครื่องมือ DSPM ผลปกติ', '1B230');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B231 การตรวจคัดกรองพัฒนาการสมวัยด้านการใช้ภาษาโดยเครื่องมือ DSPM สงสัยล่าช้า ส่งเสริมพัฒนาการใน 1 เดือน', '1B231');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B232 การตรวจคัดกรองพัฒนาการสมวัยด้านการใช้ภาษาโดยเครื่องมือ DSPM ผลล่าช้า ส่งเพื่อประเมิน/รักษาต่อ', '1B232');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B233 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการใช้ภาษาโดยเครื่องมือ DSPM ผลปกติ', '1B233');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B234 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการใช้ภาษาโดยเครื่องมือ DSPM สงสัยล่าช้า ส่งเสริมพัฒนาการใน 1 เดือน', '1B234');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B235 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการใช้ภาษาโดยเครื่องมือ DSPM ผลล่าช้า ส่งเพื่อประเมิน/รักษาต่อ', '1B235');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B236 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการใช้ภาษาโดยเครื่องมือ DAIM ผลปกติ', '1B236');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B237 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการใช้ภาษาโดยเครื่องมือ DAIM ผลล่าช้า ส่งเพื่อประเมิน/รักษาต่อ', '1B237');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B239 การตรวจคัดกรอง/แบบเฝ้าระวังพัฒนาการสมวัยด้านการใช้ภาษาโดยเครื่องมือ DSPM และหรือ DAIM ไม่ระบุรายละเอียด', '1B239');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B24', '1B24');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B240 การตรวจคัดกรองพัฒนาการสมวัยด้านการช่วยเหลือตัวเองและสังคมโดยเครื่องมือ DSPM ผลปกติ', '1B240');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B241 การตรวจคัดกรองพัฒนาการสมวัยด้านการช่วยเหลือตัวเองและสังคมโดยเครื่องมือ DSPM สงสัยล่าช้า ส่งเสริมพัฒนาการใน 1 เดือน', '1B241');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B242 การตรวจคัดกรองพัฒนาการสมวัยด้านการช่วยเหลือตัวเองและสังคมโดยเครื่องมือ DSPM ผลล่าช้าส่งเพื่อประเมิน/รักษาต่อ', '1B242');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B243 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการช่วยเหลือตัวเองและสังคมโดยเครื่องมือ DSPM ผลปกติ', '1B243');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B244 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการช่วยเหลือตัวเองและสังคมโดยเครื่องมือ DSPM สงสัยล่าช้า ส่งเสริมพัฒนาการใน 1 เดือน', '1B244');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B245 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการใช้ภาด้านการช่วยเหลือตัวเองและสังคม โดยเครื่องมือ DSPM ผลล่าช้า ส่งเพื่อประเมิน/รักษาต่อ', '1B245');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B246 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการช่วยเหลือตัวเองและสังคมโดยเครื่องมือ DAIM ผลปกติ', '1B246');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B247 การตรวจแบบเฝ้าระวังพัฒนาการสมวัยด้านการช่วยเหลือตัวเองและสังคมโดยเครื่องมือ DAIM ผลล่าช้า ส่งเพื่อประเมิน/รักษาต่อ', '1B247');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B249 การตรวจคัดกรอง/แบบเฝ้าระวังพัฒนาการสมวัยด้านการช่วยเหลือตัวเองและสังคมโดยเครื่องมือ DSPMและหรือ DAIM ไม่ระบุรายละเอียด', '1B249');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B25', '1B25');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B250 การตรวจประเมินระบบประสาทและพัฒนาการอายุแรกเกิด โดยเครื่องมือ DAIM ข้อที่ 1-3 (ตรวจปฏิกิริยา ตรวจความตึงตัวของกล้ามเนื้อ และตรวจข้อเท้า) ผ่าน', '1B250');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B251 การตรวจประเมินระบบประสาทและพัฒนาการอายุแรกเกิด โดยเครื่องมือ DAIMข้อที่ 1-3 (ตรวจปฏิกิริยา ตรวจความตึงตัวของกล้ามเนื้อ และตรวจข้อเท้า) ไม่ผ่าน ส่งเพื่อประเมิน/รักษาต่อ', '1B251');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B252 การตรวจประเมินระบบประสาทและพัฒนาการอายุ 1 เดือน โดยเครื่องมือ DAIM ข้อที่ 4 (ตรวจการเหยียดแขนและขา) ผ่าน', '1B252');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B253 การตรวจประเมินระบบประสาทและพัฒนาการอายุ 1 เดือน โดยเครื่องมือ DAIM ข้อที่ 4 (ตรวจการเหยียดแขนและขา) ไม่ผ่าน ส่งเพื่อประเมิน/รักษาต่อ', '1B253');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B254 การตรวจประเมินระบบประสาทและพัฒนาการอายุ 3-4 เดือน โดยเครื่องมือ DAIM ข้อที่ 5 (ตรวจการกำมือ) ผ่าน', '1B254');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B255 การตรวจประเมินระบบประสาทและพัฒนาการอายุ 3-4 เดือน โดยเครื่องมือ DAIM ข้อที่ 5 (ตรวจการกำมือ) ไม่ผ่าน ส่งเพื่อประเมิน/รักษาต่อ', '1B255');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B256 การตรวจประเมินระบบประสาทและพัฒนาการอายุ 10-12 เดือน โดยเครื่องมือ DAIM ข้อที่ 6 (ตรวจการกางแขน) ผ่าน', '1B256');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B257 การตรวจประเมินระบบประสาทและพัฒนาการอายุ 10-12 เดือน โดยเครื่องมือ DAIM ข้อที่ 6 (ตรวจการกางแขน) ไม่ผ่าน ส่งเพื่อประเมิน/รักษาต่อ', '1B257');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B258 การตรวจประเมินระบบประสาทและพัฒนาการอายุ 55-60 เดือน โดยเครื่องมือ DAIM ข้อที่ 7 (เดินต่อส้นเท้า) ผ่าน', '1B258');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B259 การตรวจประเมินระบบประสาทและพัฒนาการอายุ 55-60 เดือน โดยเครื่องมือ DAIM ข้อที่ 7 (เดินต่อส้นเท้า) ไม่ผ่าน ส่งเพื่อประเมิน/รักษาต่อ', '1B259');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B3', '1B3');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B30 ผลการตรวจคัดกรองมะเร็งปากมดลูก', '1B30');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B31 ผลการตรวจคัดกรองธาลาสซีเมีย', '1B31');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>>1B4', '1B4');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B40 ผลการตรวจคัดกรองมะเร็งปากมดลูก', '1B40');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B41 ผลการตรวจคัดกรองธาลาสซีเมีย', '1B41');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B260 ผลการตรวจคัดกรองพัฒนาการสมวัยโดยเครื่องมือ DSPM ผลปกติ', '1B260');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B261 ผลการตรวจคัดกรองพัฒนาการสมวัยโดยเครื่องมือ DSPM สงสัยล่าช้า ส่งเสริมพัฒนาการใน 1 เดือน', '1B261');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B262 ผลการตรวจคัดกรองพัฒนาการสมวัยโดยเครื่องมือ DSPM สงสัยล่าช้า ส่งต่อทันที', '1B262');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B51 ผู้มารับบริการมีพฤติกรรมเคยสูบบุหรี่แต่เลิกแล้ว', '1B51');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B52 ผู้มารับบริการมีพฤติกรรมไม่เคยสูบบุหรี่', '1B52');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B509 ผู้มารับบริการมีพฤติกรรมสูบบุหรี่ ไม่ระบุรายละเอียด', '1B509');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B530 การให้คำแนะนำผู้ติดบุหรี่แบบสั้น (Brief Advice)', '1B530');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B531 การให้คำปรึกษาเพื่อการเลิกบุหรี่ (Counseling Advice)', '1B531');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B532 การให้คำปรึกษาและให้ยาเพื่อเลิกบุหรี่ (Counseling Advice + Medicine)', '1B532');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B542 การติดตามผู้ติดบุหรี่ ผลไม่สูบแล้ว', '1B542');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B506 ผู้มารับบริการมีพฤติกรรมสูบบุหรี่มวนแรกหลังตื่นนอน 1 ชั่วโมง หรือมากกว่า', '1B506');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B540 การติดตามผู้ติดบุหรี่ ระยะเวลา 1 เดือน ผลยังสูบอยู่ปริมาณ/จำนวนมวน เท่าเดิม', '1B540');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B541 การติดตามผู้ติดบุหรี่ ระยะเวลา 1 เดือน ผลลดปริมาณ/จำนวนมวนที่สูบลงได้', '1B541');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B550 การติดตามผู้ติดบุหรี่ ระยะเวลา 3 เดือน ผลยังสูบบุหรี่อยู่ปริมาณ/จำนวนมวนเท่าเดิม', '1B550');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B551 การติดตามผู้ติดบุหรี่ ระยะเวลา 3 เดือน ผลลดปริมาณ/จำนวนมวนที่สูบลงได้', '1B551');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B552 การติดตามผู้ติดบุหรี่ ระยะเวลา 3 เดือน ผลไม่สูบแล้ว', '1B552');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B560 การติดตามผู้ติดบุหรี่ ระยะเวลา 6 เดือน ผลยังสูบบุหรี่อยู่ปริมาณ/จำนวนมวนเท่าเดิม', '1B560');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B561 การติดตามผู้ติดบุหรี่ ระยะเวลา 6 เดือน ผลลดปริมาณ/จำนวนมวนที่สูบลงได้', '1B561');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B562 การติดตามผู้ติดบุหรี่ ระยะเวลา 6 เดือน ผลไม่สูบแล้ว', '1B562');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B503 ผู้มารับบริการมีพฤติกรรมสูบบุหรี่ 20 มวนขึ้นไปต่อวัน', '1B503');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B504 ผู้มารับบริการมีพฤติกรรมสูบบุหรี่มวนแรกหลังตื่นนอน น้อยกว่า 30 นาที', '1B504');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B501 ผู้มารับบริการมีพฤติกรรมสูบบุหรี่ 1-10 มวนต่อวัน', '1B501');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B505 ผู้มารับบริการมีพฤติกรรมสูบบุหรี่มวนแรกหลังตื่นนอน มากกว่า 30 นาที แต่น้อยกว่า 1 ชั่วโมง', '1B505');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B502 ผู้มารับบริการมีพฤติกรรมสูบบุหรี่ 11-19 มวนต่อวัน', '1B502');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1283 - การตรวจคัดกรองภาวะกลั้นปัสสาวะในผู้สูงอายุ', '1B1283');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1284 - การตรวจคัดกรองภาวะกลั้นปัสสาวะในผู้สูงอายุ ไม่มีปัญหา', '1B1284');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1285 - การตรวจคัดกรองภาวะกลั้นปัสสาวะในผู้สูงอายุ มีปัญหา', '1B1285');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B270 การกระตุ้นพัฒนาการเด็กล่าช้าโดยเครื่องมือ TEDA4I หรือเครื่องมือมาตรฐานอื่น ผลปกติ', '1B270');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B271 การกระตุ้นพัฒนาการเด็กล่าช้าโดยเครื่องมือ TEDA4I หรือเครื่องมือมาตรฐานอื่น ผลล่าช้า ด้านการเคลื่อนไหว', '1B271');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B272 การกระตุ้นพัฒนาการเด็กล่าช้าโดยเครื่องมือ TEDA4I หรือเครื่องมือมาตรฐานอื่น ผลล่าช้า ด้านกล้ามเนื้อมัดเล็กและสติปัญญา', '1B272');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B273 การกระตุ้นพัฒนาการเด็กล่าช้าโดยเครื่องมือ TEDA4I หรือเครื่องมือมาตรฐานอื่น ผลล่าช้า ด้านความเข้าใจภาษา', '1B273');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B274 การกระตุ้นพัฒนาการเด็กล่าช้าโดยเครื่องมือ TEDA4I หรือเครื่องมือมาตรฐานอื่น ผลล่าช้า ด้านการใช้ภาษา', '1B274');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B275 การกระตุ้นพัฒนาการเด็กล่าช้าโดยเครื่องมือ TEDA4I หรือเครื่องมือมาตรฐานอื่น ผลล่าช้า ด้านการช่วยเหลือตนเองและสังคม', '1B275');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0060 ตรวจคัดกรองความเสี่ยง/โรคมะเร็งลำไส้ ได้ผลลบ', '1B0060');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0061 ตรวจคัดกรองความเสี่ยง/โรคมะเร็งลำไส้ ได้ผลบวก', '1B0061');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B1144 การตรวจคัดกรองสมรรถภาพการได้ยิน มีผลไม่ผ่านเกณฑ์ เมื่อเทียบผลการตรวจกับ Baseline audiogram (พบ 15 dB-shift และไม่ได้รับการตรวจยืนยัน: Confirmation audiogram ภายใน 30 วัน)', '1B1144');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B209 การตรวจคัดกรอง/แบบเฝ้าระวังพัฒนาการสมวัยด้านการเคลื่อนไหวโดยเครื่องมือ DSPM และ หรือ DAIM ไม่ระบุรายละเอียด', '1B209');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B600 ผู้มารับบริการไม่เคยดื่มเครื่องดื่มแอลกอฮอล์ ตลอดชีวิตที่ผ่านมา ', '1B600');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B601 ผู้มารับบริการเคยดื่มเครื่องดื่มแอลกอฮอล์ แต่เลิกดื่มมาแล้ว 1 ปีขึ้นไป', '1B601');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B602 ผู้มารับบริการดื่มเครื่องดื่มแอลกอฮอล์ในระดับเสี่ยงต่ำ (คะแนน 0-10)', '1B602');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B603 ผู้มารับบริการดื่มเครื่องดื่มแอลกอฮอล์ในระดับเสี่ยงปานกลาง (คะแนน 11-26)', '1B603');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B604 ผู้มารับบริการดื่มเครื่องดื่มแอลกอฮอล์ในระดับเสี่ยงสูง (คะแนนตั้งแต่ 27 ขึ้นไป)', '1B604');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B609 ผู้มารับบริการดื่มเครื่องดื่มแอลกอฮอล์ ไม่ระบุรายละเอียด', '1B609');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B610 การให้คำแนะนำ (brief advice)', '1B610');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B611 การให้คำปรึกษาแบบสั้น (brief counseling)', '1B611');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B612 การส่งต่อเพื่อรับการประเมินและการบำบัดโดยผู้เชี่ยวชาญ (refer)', '1B612');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1F301 การให้คำปรึกษาด้านสุขภาพ กลุ่มชายที่มีเพศสัมพันธ์กับชาย', '1F301');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1F302 การให้คำปรึกษาด้านสุขภาพ กลุ่มสาวประเภทสอง', '1F302');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1F31 การให้คำปรึกษาด้านสุขภาพ กลุ่มที่มีคู่นอนหลายคนเชิงพาณิชย์', '1F31');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1F32 การให้คำปรึกษาด้านสุขภาพ กลุ่มผู้ใช้ยาเสพติดประเภทฉีด', '1F32');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1F33 การให้คำปรึกษาด้านสุขภาพ กลุ่มคู่ผู้ติดเชื้อ', '1F33');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1F38 การให้คำปรึกษาด้านสุขภาพ กลุ่มอื่น ๆ', '1F38');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B0046 การคัดกรองมะเร็งปากมดลูก ด้วยวิธี HPV Genotype Testing', '1B0046');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B030 การประเมิน ผู้ป่วยจิตเวชที่มีความเสี่ยงสูง พบทำร้ายตนเองด้วยวิธีรุนแรง  มุ่งหวังให้เสียชีวิต', '1B030');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B031 การประเมิน ผู้ป่วยจิตเวชที่มีความเสี่ยงสูง พบทำร้ายผู้อื่นด้วยวิธีรุนแรง/ก่อเหตุการณ์รุนแรงในชุมชน', '1B031');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B032 การประเมิน ผู้ป่วยจิตเวชที่มีความเสี่ยงสูง พบมีอาการหลงผิด มีความคิดทำร้าย ผู้อื่นให้ถึงกับชีวิต หรือมุ่งร้ายผู้อื่นแบบเฉพาะเจาะจง เช่น ระบุชื่อคนที่จะมุ่งร้าย', '1B032');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B033 การประเมิน ผู้ป่วยจิตเวชที่มีความเสี่ยงสูง พบก่อคดีอาชญากรรมรุนแรง  (ฆ่า พยายามฆ่า ข่มขืน วางเพลิง)', '1B033');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('<<ยกเลิก>> 1B034', '1B034');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B620 การติดตามพฤติกรรมผู้มีปัญหาการดื่มสุรา ระยะเวลา 1 เดือน ไม่ดื่มเลย', '1B620');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B621 การติดตามพฤติกรรมผู้มีปัญหาการดื่มสุรา ระยะเวลา 1 เดือน ดื่มลดลง', '1B621');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B622 การติดตามพฤติกรรมผู้มีปัญหาการดื่มสุรา ระยะเวลา 1 เดือน ดื่มเท่าเดิม', '1B622');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B623 การติดตามพฤติกรรมผู้มีปัญหาการดื่มสุรา ระยะเวลา 1 เดือน ดื่มมากขึ้น', '1B623');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B630 การติดตามพฤติกรรมผู้มีปัญหาการดื่มสุรา ระยะเวลา 3 เดือน ไม่ดื่มเลย', '1B630');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B631 การติดตามพฤติกรรมผู้มีปัญหาการดื่มสุรา ระยะเวลา 3 เดือน ดื่มลดลง', '1B631');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B632 การติดตามพฤติกรรมผู้มีปัญหาการดื่มสุรา ระยะเวลา 3 เดือน ดื่มเท่าเดิม', '1B632');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B633 การติดตามพฤติกรรมผู้มีปัญหาการดื่มสุรา ระยะเวลา 3 เดือน ดื่มมากขึ้น', '1B633');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B640 การติดตามพฤติกรรมผู้มีปัญหาการดื่มสุรา ระยะเวลา 6 เดือน ดื่มลดลง', '1B640');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B641 การติดตามพฤติกรรมผู้มีปัญหาการดื่มสุรา ระยะเวลา 6 เดือน ดื่มลดลง', '1B641');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B642 การติดตามพฤติกรรมผู้มีปัญหาการดื่มสุรา ระยะเวลา 6 เดือน ดื่มเท่าเดิม', '1B642');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B643 การติดตามพฤติกรรมผู้มีปัญหาการดื่มสุรา ระยะเวลา 6 เดือน ดื่มมากขึ้น', '1B643');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B650 การติดตามพฤติกรรมผู้มีปัญหาการดื่มสุรา ระยะเวลา 12 เดือน ไม่ดื่มเลย', '1B650');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B651 การติดตามพฤติกรรมผู้มีปัญหาการดื่มสุรา ระยะเวลา 12 เดือน ดื่มลดลง', '1B651');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B652 การติดตามพฤติกรรมผู้มีปัญหาการดื่มสุรา ระยะเวลา 12 เดือน ดื่มเท่าเดิม', '1B652');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B653 การติดตามพฤติกรรมผู้มีปัญหาการดื่มสุรา ระยะเวลา 12 เดือน ดื่มมากขึ้น', '1B653');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1F8 การให้บริการติดตาม/ให้คำปรึกษา/ให้ความรู้และแนะนำทางด้านสุขภาพอื่น', '1F8');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B036 การประเมิน ผู้ป่วยจิตเวชที่มีความเสี่ยงสูงต่อการก่อความรุนแรง พบว่าปกติ', '1B036');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B037 ผู้ป่วยจิตเวชที่มีความเสี่ยงสูงต่อการก่อความรุนแรง พบว่าก่อเหตุความรุนแรง  ทำร้ายตัวเอง/ทำร้ายผู้อื่น/ก่อคดีอาชญากรรมรุนแรง ได้รับการติดตาม', '1B037');
INSERT INTO `wsc_special_type` (`pp_special_type_name`, `pp_special_code`) VALUES ('1B038 การประเมิน ผู้ป่วยจิตเวชที่มีความเสี่ยงสูงต่อการก่อความรุนแรงพบว่ามีประวัติ/อาการ อื่น', '1B038');
